export {default as DashboardPage} from './home'
export {default as NotFoundPage} from './not-found'
export {default as LoginPage} from '@/pages/authenication/sign-in'
export {default as AboutPage} from '@/pages/about/about'
export {default as DepartmentContactPage} from '@/pages/contact/department'
export {default as SocialMediaPage} from '@/pages/contact/social-media'
export {default as MessagePage} from '@/pages/contact/message'
export {default as SubscribersPage} from '@/pages/contact/subscribers'
